apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: govukdiff-cert
spec:
  dnsNames:
  - govukdiff.njk.onl
  - gitgovuk.njk.onl
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-production
  secretName: govukdiff-cert
